/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package omamgkirjasto;

//import java.awt.Component;
import java.awt.print.PrinterException;
//import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.MessageFormat;
//import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author lentt
 */
public class MangaKirjasto extends javax.swing.JFrame {

    luoYhteys db = new luoYhteys();

    /**
     * Creates new form MgKirjasto
     */
    public MangaKirjasto() throws ClassNotFoundException, SQLException {
        initComponents();

        /**
         * Tyhjennetään tekstikentät. ladataan uudestaan taulukot, valikot ja
         * ID:t-idtekstikenttiin. lasketaan raulukkojen rivit uudellen.
         */
        tableloadMg(tbManga);
        comboloadMg(comboManga);
        idloadManga(txtMgID);

        tableloadKjs(tbKirjasto);
        comboload2(comboKirjasto);
        idloadKirjasto(txtKjsID);

        rivinlasku();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbKirjasto = new javax.swing.JTable();
        lblKjsRivi = new javax.swing.JLabel();
        btKjsTulosta = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbManga = new javax.swing.JTable();
        lblMgRivi = new javax.swing.JLabel();
        btMgTulosta = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtMgID = new javax.swing.JTextField();
        txtMgNimi = new javax.swing.JTextField();
        txtMgTekija = new javax.swing.JTextField();
        txtMgKustantaja = new javax.swing.JTextField();
        txtMgKieli = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btMgLisaa = new javax.swing.JButton();
        btMgPaivita = new javax.swing.JButton();
        btMgPoista = new javax.swing.JButton();
        btTyhjenna = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        comboManga = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txtKjsID = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtKjsNro = new javax.swing.JTextField();
        comboKirjasto = new javax.swing.JComboBox<>();
        jPanel7 = new javax.swing.JPanel();
        btKjsLisaa = new javax.swing.JButton();
        btKjsPaivita = new javax.swing.JButton();
        btKjsPoista = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        comboMgHaku = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        txtMgHaku = new javax.swing.JTextField();
        btMgHae = new javax.swing.JButton();
        btMgTyhjenna = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        comboKjsHaku = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        txtKjsHaku = new javax.swing.JTextField();
        btKjsHae = new javax.swing.JButton();
        btKjsTyhjenna = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        btValikko = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 255, 0));

        jTabbedPane1.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N

        tbKirjasto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nimi", "Tekijä", "Kustantaja", "Kieli", "Nro"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbKirjasto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbKirjastoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbKirjasto);
        if (tbKirjasto.getColumnModel().getColumnCount() > 0) {
            tbKirjasto.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        lblKjsRivi.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        btKjsTulosta.setText("Tulosta");
        btKjsTulosta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btKjsTulostaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btKjsTulosta, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblKjsRivi, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 726, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblKjsRivi, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btKjsTulosta))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Kirjasto", jPanel3);

        tbManga.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nimi", "Tekijä", "Kustantaja", "Kieli"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbManga.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbMangaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbManga);
        if (tbManga.getColumnModel().getColumnCount() > 0) {
            tbManga.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        lblMgRivi.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        btMgTulosta.setText("Tulosta");
        btMgTulosta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMgTulostaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 738, Short.MAX_VALUE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btMgTulosta, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblMgRivi, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 530, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblMgRivi, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btMgTulosta))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Mangat", jPanel4);

        jTabbedPane2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTabbedPane2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N

        jLabel5.setText("Manga ID:");

        jLabel1.setText("Mangan nimi:");

        jLabel2.setText("Tekijä:");

        jLabel3.setText("Kustantaja:");

        jLabel4.setText("Kieli:");

        txtMgID.setEditable(false);

        btMgLisaa.setText("Lisää");
        btMgLisaa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMgLisaaActionPerformed(evt);
            }
        });

        btMgPaivita.setText("Päivitä");
        btMgPaivita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMgPaivitaActionPerformed(evt);
            }
        });

        btMgPoista.setText("Poista");
        btMgPoista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMgPoistaActionPerformed(evt);
            }
        });

        btTyhjenna.setText("Tyhjennä");
        btTyhjenna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btTyhjennaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btMgPoista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btMgPaivita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btMgLisaa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btTyhjenna)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btMgLisaa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btMgPaivita)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btMgPoista)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btTyhjenna)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMgKustantaja, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                            .addComponent(txtMgKieli)))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(50, 50, 50)
                            .addComponent(txtMgTekija, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel5))
                            .addGap(12, 12, 12)
                            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtMgID, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtMgNimi)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtMgID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtMgNimi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtMgTekija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtMgKustantaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(txtMgKieli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        comboManga.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                comboMangaPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        comboManga.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comboMangaMouseClicked(evt);
            }
        });
        comboManga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMangaActionPerformed(evt);
            }
        });

        jLabel6.setText("Kirjasto ID:");

        txtKjsID.setEditable(false);

        jLabel7.setText("Nro:");

        comboKirjasto.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                comboKirjastoPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        btKjsLisaa.setText("Lisää");
        btKjsLisaa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btKjsLisaaActionPerformed(evt);
            }
        });

        btKjsPaivita.setText("Päivitä");
        btKjsPaivita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btKjsPaivitaActionPerformed(evt);
            }
        });

        btKjsPoista.setText("Poista");
        btKjsPoista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btKjsPoistaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btKjsPaivita, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btKjsLisaa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btKjsPoista, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btKjsLisaa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btKjsPaivita)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btKjsPoista)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(comboManga, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboKirjasto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(18, 18, 18)
                            .addComponent(txtKjsID, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addGap(58, 58, 58)
                            .addComponent(txtKjsNro, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtKjsID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addComponent(comboManga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtKjsNro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(comboKirjasto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(83, 83, 83))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Valinnat", jPanel8);

        jLabel9.setText("Manga haku:");

        jLabel10.setText("Valitse millä haetaan:");

        comboMgHaku.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NIMI", "TEKIJA", "KUSTANTAJA", "KIELI" }));

        jLabel11.setText("Kirjoita hakuehto:");

        btMgHae.setText("Hae");
        btMgHae.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMgHaeActionPerformed(evt);
            }
        });

        btMgTyhjenna.setText("Tyhjennä");
        btMgTyhjenna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMgTyhjennaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(comboMgHaku, 0, 155, Short.MAX_VALUE)
                            .addComponent(txtMgHaku))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btMgHae, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btMgTyhjenna))))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(comboMgHaku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btMgHae))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtMgHaku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btMgTyhjenna))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel12.setText("Kirjasto haku:");

        jLabel13.setText("Valitse millä haetaan:");

        comboKjsHaku.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NIMI", "TEKIJA", "KUSTANTAJA", "KIELI", "NRO" }));

        jLabel14.setText("Kirjoita hakuehto:");

        btKjsHae.setText("Hae");
        btKjsHae.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btKjsHaeActionPerformed(evt);
            }
        });

        btKjsTyhjenna.setText("Tyhjennä");
        btKjsTyhjenna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btKjsTyhjennaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(comboKjsHaku, 0, 157, Short.MAX_VALUE)
                            .addComponent(txtKjsHaku))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btKjsHae, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btKjsTyhjenna, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(comboKjsHaku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btKjsHae))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13)))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtKjsHaku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btKjsTyhjenna))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(234, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Haku", jPanel9);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(79, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jLabel8.setFont(new java.awt.Font("Arial Black", 0, 48)); // NOI18N
        jLabel8.setText("Manga kirjasto");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(122, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        btValikko.setText("Valikko");
        btValikko.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btValikkoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(316, 316, 316)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btValikko, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(btValikko, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btMgLisaaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMgLisaaActionPerformed

        try {
            //Tarkistetaan ettei tekstikentät ole tyhjiä. 
            if (txtMgNimi.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Anna Nimi!");

            } else if (txtMgTekija.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Anna Tekijä!");

            } else if (txtMgKustantaja.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Anna Kustantaja!");

            } else if (txtMgKieli.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Anna Kieli!");

            } else {

                /**
                 * Kun on tarkistettu että teksti-kentissä on tekstiä niin
                 * haetaan ne ja tallennetaan tietokantaan. ID on
                 * automaattisesti generoitu
                 */
                db.putData("INSERT INTO MANGA(NIMI,TEKIJA,KUSTANTAJA,KIELI) "
                        + "values('" + txtMgNimi.getText() + "','" + txtMgTekija.getText() + "','" + txtMgKustantaja.getText()
                        + "','" + txtMgKieli.getText() + "')");

                System.out.println("Alkaa22");
                /**
                 * Tyhjennetään tekstikentät ladataan uudestaan taulukot,
                 * valikot ja id:t-tekstikenttiin. Asetetaan Manga välilehti
                 * valituksi lasketaan raulukkojen rivit uudellen.
                 */
                clear();
                tableloadMg(tbManga);
                comboloadMg(comboManga);
                idloadManga(txtMgID);

                tableloadKjs(tbKirjasto);
                comboload2(comboKirjasto);
                idloadKirjasto(txtKjsID);
                jTabbedPane1.setSelectedIndex(1);
                rivinlasku();
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MangaKirjasto.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println(ex);
        } catch (SQLException ex) {
            Logger.getLogger(MangaKirjasto.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println(ex);
        }


    }//GEN-LAST:event_btMgLisaaActionPerformed

    private void tbMangaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbMangaMouseClicked
        //Klikkaamalla taulukkossa jotakin tietoa ne päivittyvät tekstikenttiin
        //Valitun tiedon ID (paikka 0) lisätään Mangan nimi:-tekstikenttään
        txtMgID.setText(String.valueOf(tbManga.getValueAt(tbManga.getSelectedRow(), 0)));
        //Valitun tiedon nimi (paikka 1) lisätään Mangan nimi:-tekstikenttään
        txtMgNimi.setText(String.valueOf(tbManga.getValueAt(tbManga.getSelectedRow(), 1)));
        //Valitun tiedon tekijä (paikka 2) lisätään tekijä:-tekstikenttään
        txtMgTekija.setText(String.valueOf(tbManga.getValueAt(tbManga.getSelectedRow(), 2)));
        //Valitun tiedon kustantaja (paikka 3) lisätään kustantaja:-tekstikenttään
        txtMgKustantaja.setText(String.valueOf(tbManga.getValueAt(tbManga.getSelectedRow(), 3)));
        //Valitun tiedon kieli (paikka 4) lisätään kieli:-tekstikenttään
        txtMgKieli.setText(String.valueOf(tbManga.getValueAt(tbManga.getSelectedRow(), 4)));

        try {
            //Muutetaan taulukosta valitun rivin ID int-muotoon
            int valittuID = Integer.parseInt(String.valueOf(tbManga.getValueAt(tbManga.getSelectedRow(), 0)));
            ResultSet rset;
            //Haetaan tiedot tietokannasta
            rset = db.getData("SELECT * FROM MANGA where ID= " + valittuID);
            //Valitaan valikosta taulukon valittu rivi
            while (rset.next()) {
                comboManga.setSelectedItem(rset.getInt("ID") + " , " + rset.getString("NIMI") + " , " + rset.getString("KIELI"));
            }
            //Tyhjennetään txtKjsNro tekstikenttä
            txtKjsNro.setText(null);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MangaKirjasto.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println(ex);
        } catch (SQLException ex) {
            Logger.getLogger(MangaKirjasto.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println(ex);
        }
    }//GEN-LAST:event_tbMangaMouseClicked

    private void btMgPaivitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMgPaivitaActionPerformed
        try {
            //Tarkistetaan ettei tekstikentät ole tyhjiä.
            if (txtMgNimi.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Anna Nimi!");

            } else if (txtMgTekija.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Anna Tekijä!");

            } else if (txtMgKustantaja.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Anna Kustantaja!");

            } else if (txtMgKieli.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Anna Kieli!");

            } else {
                /**
                 * Kun kaikissa kentissä on tietoa niin, haetaan päivitettävän
                 * tiedon id comboManga:sta ja muutetaan se int-muotoon
                 */
                String valinta = (String) comboManga.getSelectedItem();
                String[] nimet = valinta.split(" ");
                int mangaId = Integer.parseInt(nimet[0]);

                String nimi = txtMgNimi.getText();
                String tekija = txtMgTekija.getText();
                String kustantaja = txtMgKustantaja.getText();
                String kieli = txtMgKieli.getText();

                //Haetaan tiedot tekstikentistä ja päivitetään tiedot tietokantaan
                db.putData("UPDATE MANGA SET NIMI  ='" + nimi + "', TEKIJA = '" + tekija + "', KUSTANTAJA ='" + kustantaja + "',  KIELI='" + kieli + "'  WHERE ID = " + mangaId);

                /**
                 * Tyhjennetään tekstikentät ladataan uudestaan taulukot,
                 * valikot ja id:t-tekstikenttiin. Asetetaan Manga välilehti
                 * valituksi lasketaan raulukkojen rivit uudellen.
                 */
                clear();
                tableloadMg(tbManga);
                comboloadMg(comboManga);
                idloadManga(txtMgID);

                tableloadKjs(tbKirjasto);
                comboload2(comboKirjasto);
                idloadKirjasto(txtKjsID);
                jTabbedPane1.setSelectedIndex(1);
                rivinlasku();
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MangaKirjasto.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println(ex);
        } catch (SQLException ex) {
            Logger.getLogger(MangaKirjasto.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println(ex);
        }
    }//GEN-LAST:event_btMgPaivitaActionPerformed

    private void btMgPoistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMgPoistaActionPerformed
        try {
            /**
             * Haetaan poistettavan tiedon id comboManga:sta ja muutetaan se
             * int-muotoon. Poistetaan tieto MANGA ja MGKIRJASTO:sta Manga ID:n
             * mukaan
             */
            String valinta = (String) comboManga.getSelectedItem();
            String[] nimet = valinta.split(" ");
            int mangaId = Integer.parseInt(nimet[0]);
            db.putData("DELETE FROM MANGA WHERE ID = " + mangaId);
            db.putData("DELETE FROM MGKIRJASTO WHERE ID_MANGA = " + mangaId);

            /**
             * Tyhjennetään tekstikentät ladataan uudestaan taulukot, valikot ja
             * id:t-tekstikenttiin. Asetetaan Manga välilehti valituksi
             * lasketaan raulukkojen rivit uudellen.
             */
            clear();
            tableloadMg(tbManga);
            comboloadMg(comboManga);
            idloadManga(txtMgID);

            tableloadKjs(tbKirjasto);
            comboload2(comboKirjasto);
            idloadKirjasto(txtKjsID);
            jTabbedPane1.setSelectedIndex(1);
            rivinlasku();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MangaKirjasto.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MangaKirjasto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btMgPoistaActionPerformed

    private void comboMangaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboMangaMouseClicked

    }//GEN-LAST:event_comboMangaMouseClicked

    private void comboMangaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMangaActionPerformed

    }//GEN-LAST:event_comboMangaActionPerformed

    private void comboMangaPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_comboMangaPopupMenuWillBecomeInvisible
        try {
            /**
             * Haetaan valittavan tiedon id comboManga:sta ja muutetaan se
             * int-muotoon. Haetaan tiedot tietokannasta. Lisätään ne
             * tekstikenttiin
             */
            String valinta = (String) comboManga.getSelectedItem();
            String[] nimet = valinta.split(" ");
            int mangaID = Integer.parseInt(nimet[0]);

            ResultSet rset = db.getData("SELECT * FROM MANGA WHERE ID =" + mangaID);
            while (rset.next()) {

                txtMgID.setText(rset.getString("ID"));
                txtMgNimi.setText(rset.getString("NIMI"));
                txtMgTekija.setText(rset.getString("TEKIJA"));
                txtMgKustantaja.setText(rset.getString("KUSTANTAJA"));
                txtMgKieli.setText(rset.getString("KIELI"));
            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MangaKirjasto.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MangaKirjasto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_comboMangaPopupMenuWillBecomeInvisible

    private void btKjsLisaaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btKjsLisaaActionPerformed

        try {
            //Tarkistetaan ettei Nro tekstikenttä ole tyhjä
            if (txtKjsNro.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Anna Numero!");

            } else {
                /**
                 * Haetaan valittavan tiedon id comboManga:sta ja muutetaan se
                 * int-muotoon. Haetaan MANGA:n tiedot tietokannasta. Lisätään
                 * MGKIRJASTO:on mangan id ja Nro haetaan tekstikentästä
                 */
                String valinta = (String) comboManga.getSelectedItem();
                String[] nimet = valinta.split(" ");
                int mangaId = Integer.parseInt(nimet[0]);

                ResultSet rset = db.getData("SELECT * FROM MANGA WHERE ID = " + mangaId);

                while (rset.next()) {
                    db.putData("INSERT INTO MGKIRJASTO(ID_MANGA,NRO) VALUES(" + rset.getInt("ID") + ",'" + txtKjsNro.getText() + "')");
                }

                /**
                 * Tyhjennetään tekstikentät ladataan uudestaan taulukot,
                 * valikot ja id:t-tekstikenttiin. Asetetaan Manga välilehti
                 * valituksi lasketaan raulukkojen rivit uudellen.
                 */
                clear();
                tableloadMg(tbManga);
                comboloadMg(comboManga);
                idloadManga(txtMgID);

                tableloadKjs(tbKirjasto);
                comboload2(comboKirjasto);
                idloadKirjasto(txtKjsID);

                jTabbedPane1.setSelectedIndex(0);
                rivinlasku();
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MangaKirjasto.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println(ex);
        } catch (SQLException ex) {
            Logger.getLogger(MangaKirjasto.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println(ex);
        }

    }//GEN-LAST:event_btKjsLisaaActionPerformed

    private void btKjsPaivitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btKjsPaivitaActionPerformed
        try {
            //Tarkistetaan ettei Nro tekstikenttä ole tyhjä
            if (txtKjsNro.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null, "Anna Numaro!");

            } else {
                /**
                 * Haetaan valittavan tiedon id comboManga:sta ja
                 * comboKirjasto:sta Muutetaan ne int-muotoon. Päivitetään
                 * MGKIRJASTO:on mangan id ja Nro, joka haetaan tekstikentästä
                 */
                String valinta = (String) comboManga.getSelectedItem();
                String[] nimet = valinta.split(" ");
                int mangaId = Integer.parseInt(nimet[0]);

                String valintaKjs = (String) comboKirjasto.getSelectedItem();
                String[] nimetKjs = valintaKjs.split(" ");
                int kirjastoId = Integer.parseInt(nimetKjs[0]);

                String nro = txtKjsNro.getText();

                db.putData("UPDATE MGKIRJASTO SET ID_MANGA  =" + mangaId + ", NRO = '" + nro + "'  WHERE KIRJASTOID =" + kirjastoId);

                /**
                 * Tyhjennetään tekstikentät ladataan uudestaan taulukot,
                 * valikot ja id:t-tekstikenttiin. Asetetaan Manga välilehti
                 * valituksi lasketaan raulukkojen rivit uudellen.
                 */
                clear();
                tableloadMg(tbManga);
                comboloadMg(comboManga);
                idloadManga(txtMgID);

                tableloadKjs(tbKirjasto);
                comboload2(comboKirjasto);
                idloadKirjasto(txtKjsID);

                jTabbedPane1.setSelectedIndex(0);
                rivinlasku();
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MangaKirjasto.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println(ex);
        } catch (SQLException ex) {
            Logger.getLogger(MangaKirjasto.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println(ex);
        }

    }//GEN-LAST:event_btKjsPaivitaActionPerformed

    private void btKjsPoistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btKjsPoistaActionPerformed
        try {
            /**
             * Haetaan poistettavan tiedon id comboKirjasto:sta ja muutetaan se
             * int-muotoon. Poistetaan tieto MGKIRJASTO:sta KirjastoID:n mukaan
             */
            String valinta = (String) comboKirjasto.getSelectedItem();
            String[] nimet = valinta.split(" ");
            int kirjastoId = Integer.parseInt(nimet[0]);

            db.putData("DELETE FROM MGKIRJASTO WHERE KIRJASTOID = " + kirjastoId);

            /**
             * Kutsutaan metodeja. Tyhjennetään tekstikentät ladataan uudestaan.
             * manga ja kirjasto taulukot valikot ja id:t-tekstikenttiin.
             * lasketaan raulukkojen rivit uudellen. Asetetaan Kirjasto
             * välilehti päällimmäiseksi
             */
            clear();
            tableloadMg(tbManga);
            comboloadMg(comboManga);
            idloadManga(txtMgID);

            tableloadKjs(tbKirjasto);
            comboload2(comboKirjasto);
            idloadKirjasto(txtKjsID);
            rivinlasku();
            jTabbedPane1.setSelectedIndex(0);

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MangaKirjasto.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MangaKirjasto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btKjsPoistaActionPerformed

    private void tbKirjastoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbKirjastoMouseClicked
        //Klikkaamalla taulukkossa jotakin tietoa ne päivittyvät tekstikenttiin
        //Valitun tiedon id (paikka 0) lisätään KirjastoID:-tekstikenttään
        txtKjsID.setText(String.valueOf(tbKirjasto.getValueAt(tbKirjasto.getSelectedRow(), 0)));
        //Valitun tiedon nimi (paikka 1) lisätään Mangan nimi:-tekstikenttään
        txtMgNimi.setText(String.valueOf(tbKirjasto.getValueAt(tbKirjasto.getSelectedRow(), 1)));
        //Valitun tiedon tekijä (paikka 1) lisätään tekijä:-tekstikenttään
        txtMgTekija.setText(String.valueOf(tbKirjasto.getValueAt(tbKirjasto.getSelectedRow(), 2)));
        //Valitun tiedon kustantaja (paikka 2) lisätään kustantaja:-tekstikenttään
        txtMgKustantaja.setText(String.valueOf(tbKirjasto.getValueAt(tbKirjasto.getSelectedRow(), 3)));
        //Valitun tiedon kieli (paikka 3) lisätään kieli:-tekstikenttään
        txtMgKieli.setText(String.valueOf(tbKirjasto.getValueAt(tbKirjasto.getSelectedRow(), 4)));
        //Valitun tiedon Nro (paikka 3) lisätään Nro:-tekstikenttään
        txtKjsNro.setText(String.valueOf(tbKirjasto.getValueAt(tbKirjasto.getSelectedRow(), 5)));

        try {
            //Haetaan KirjastoID taulukosta ja muutetaan se int muotoon.
            int valittuKjsID = Integer.parseInt(String.valueOf(tbKirjasto.getValueAt(tbKirjasto.getSelectedRow(), 0)));
            //Haetaan tiedot comboManga-valikkoon
            ResultSet rset = db.getData("SELECT * FROM MGKIRJASTO INNER JOIN MANGA ON MGKIRJASTO.ID_MANGA = MANGA.ID WHERE KIRJASTOID= " + valittuKjsID + "");
            //Lisätään tiedot comboManga-valikkoon
            while (rset.next()) {
                comboManga.setSelectedItem(rset.getInt("ID_MANGA") + " , " + rset.getString("NIMI") + " , " + rset.getString("KIELI"));
                //Lisätään txtMgID-kenttään Manga ID 
                txtMgID.setText(rset.getString("ID"));
            }

            //Haetaan tiedot comboKirjasto-valikkoon
            ResultSet rset2 = db.getData("SELECT * FROM MGKIRJASTO INNER JOIN MANGA ON MGKIRJASTO.ID_MANGA = MANGA.ID WHERE KIRJASTOID= " + valittuKjsID + "");
            //Lisätään tiedot comboKirjasto-valikkoon
            while (rset2.next()) {
                comboKirjasto.setSelectedItem(rset2.getInt("KIRJASTOID") + " , " + rset2.getString("NIMI") + " , " + rset2.getString("NRO"));
            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MangaKirjasto.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println(ex);
        } catch (SQLException ex) {
            Logger.getLogger(MangaKirjasto.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println(ex);
        }

    }//GEN-LAST:event_tbKirjastoMouseClicked

    private void btMgHaeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMgHaeActionPerformed
        try {
            /**
             * Kutsutaan tableloadMgHaku-metodia manga-talukkoon. lasketaan
             * raulukkojen rivituudellen. Asetetaan manga välilehti
             * päällimmäiseksi.
             */
            tableloadMgHaku(tbManga);
            rivinlasku();
            jTabbedPane1.setSelectedIndex(1);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MangaKirjasto.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MangaKirjasto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btMgHaeActionPerformed

    private void btMgTyhjennaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMgTyhjennaActionPerformed
        try {
            /**
             * Tyhjennetän manga haku kenttä. lasketaan raulukkojen
             * rivituudellen. Kutsutaan tableloadMgHaku-metodia manga-talukkoon.
             * Asetetaan manga välilehti päällimmäiseksi.
             */
            txtMgHaku.setText(null);
            rivinlasku();
            tableloadMg(tbManga);
            jTabbedPane1.setSelectedIndex(1);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MangaKirjasto.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MangaKirjasto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btMgTyhjennaActionPerformed

    private void btKjsHaeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btKjsHaeActionPerformed
        try {
            /**
             * Kutsutaan tableloadKjsHaku-metodia Kirjasto-talukkoon. lasketaan
             * raulukkojen rivituudellen. Asetetaan Kirjasto välilehti
             * päällimmäiseksi.
             */
            tableloadKjsHaku(tbKirjasto);
            rivinlasku();
            jTabbedPane1.setSelectedIndex(0);

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MangaKirjasto.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MangaKirjasto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btKjsHaeActionPerformed

    private void btKjsTyhjennaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btKjsTyhjennaActionPerformed
        try {
            /**
             * Tyhjennetän kirjasto haku kenttä. lasketaan raulukkojen
             * rivituudellen. Kutsutaan tableloadMgHaku-metodia manga-talukkoon.
             * Asetetaan manga välilehti päällimmäiseksi.
             */
            txtKjsHaku.setText(null);
            rivinlasku();
            jTabbedPane1.setSelectedIndex(0);
            tableloadKjs(tbKirjasto);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MangaKirjasto.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MangaKirjasto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btKjsTyhjennaActionPerformed

    private void btTyhjennaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btTyhjennaActionPerformed
        try {
            /**
             * Kutsutaan metodeja. Tyhjennetään tekstikentät ladataan uudestaan.
             * manga ja kirjasto taulukot valikot ja id:t-tekstikenttiin.
             * lasketaan raulukkojen rivit uudellen. Asetetaan Kirjasto
             * välilehti päällimmäiseksi
             */
            clear();
            tableloadMg(tbManga);
            comboloadMg(comboManga);
            idloadManga(txtMgID);

            tableloadKjs(tbKirjasto);
            comboload2(comboKirjasto);
            idloadKirjasto(txtKjsID);

            jTabbedPane1.setSelectedIndex(0);
            rivinlasku();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MangaKirjasto.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MangaKirjasto.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_btTyhjennaActionPerformed

    private void comboKirjastoPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_comboKirjastoPopupMenuWillBecomeInvisible
        try {
            /**
             * Haetaan valittavan tiedon id comboKirjasto:sta ja muutetaan se
             * int-muotoon. Haetaan tiedot tietokannasta. Lisätään ne
             * tekstikenttiin
             */
            String valinta = (String) comboKirjasto.getSelectedItem();
            String[] nimet = valinta.split(" ");
            int kirjastoID = Integer.parseInt(nimet[0]);

            ResultSet rset = db.getData("SELECT MGKIRJASTO.KIRJASTOID, MANGA.ID, MANGA.NIMI, MANGA.TEKIJA, MANGA.KUSTANTAJA, MANGA.KIELI, MGKIRJASTO.NRO "
                    + "FROM MGKIRJASTO INNER JOIN MANGA ON MGKIRJASTO.ID_MANGA = MANGA.ID WHERE KIRJASTOID=" + kirjastoID);
            while (rset.next()) {

                txtMgID.setText(rset.getString("ID"));
                txtMgNimi.setText(rset.getString("NIMI"));
                txtMgTekija.setText(rset.getString("TEKIJA"));
                txtMgKustantaja.setText(rset.getString("KUSTANTAJA"));
                txtMgKieli.setText(rset.getString("KIELI"));

                txtKjsID.setText(rset.getString("KIRJASTOID"));
                txtKjsNro.setText(rset.getString("NRO"));
            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MangaKirjasto.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MangaKirjasto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_comboKirjastoPopupMenuWillBecomeInvisible

    private void btKjsTulostaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btKjsTulostaActionPerformed
        /**
         * Luodaan Otsikko ja ala otsikko(Sivunumero) ja lisätään ne
         * tulostettavaan taulukkoon.
         */
        MessageFormat otsikko = new MessageFormat("Manga kirjasto");

        MessageFormat alaOtsikko = new MessageFormat("Sivu{0,number,integer}");

        try {
            tbKirjasto.print(JTable.PrintMode.FIT_WIDTH, otsikko, alaOtsikko);
        } catch (PrinterException ex) {
            Logger.getLogger(MangaKirjasto.class.getName()).log(Level.SEVERE, null, ex);
            System.err.format("VIRHE. Ei voitu tulostaa %s%n", ex.getMessage());
        }

    }//GEN-LAST:event_btKjsTulostaActionPerformed

    private void btMgTulostaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMgTulostaActionPerformed
        /**
         * Luodaan Otsikko ja ala otsikko(Sivunumero) ja lisätään ne
         * tulostettavaan taulukkoon.
         */
        MessageFormat otsikko = new MessageFormat("Mangat");

        MessageFormat alaOtsikko = new MessageFormat("Sivu{0,number,integer}");

        try {
            tbManga.print(JTable.PrintMode.FIT_WIDTH, otsikko, alaOtsikko);
        } catch (PrinterException ex) {
            Logger.getLogger(MangaKirjasto.class.getName()).log(Level.SEVERE, null, ex);
            System.err.format("VIRHE. Ei voitu tulostaa %s%n", ex.getMessage());
        }

    }//GEN-LAST:event_btMgTulostaActionPerformed

    private void btValikkoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btValikkoActionPerformed
        /**
         * Haetaan etusivu näkyville. Piilotetaan Mangakirjasto
         */
        new Etusivu().setVisible(true);

        this.setVisible(false);
    }//GEN-LAST:event_btValikkoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MangaKirjasto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MangaKirjasto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MangaKirjasto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MangaKirjasto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MangaKirjasto().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(MangaKirjasto.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(MangaKirjasto.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btKjsHae;
    private javax.swing.JButton btKjsLisaa;
    private javax.swing.JButton btKjsPaivita;
    private javax.swing.JButton btKjsPoista;
    private javax.swing.JButton btKjsTulosta;
    private javax.swing.JButton btKjsTyhjenna;
    private javax.swing.JButton btMgHae;
    private javax.swing.JButton btMgLisaa;
    private javax.swing.JButton btMgPaivita;
    private javax.swing.JButton btMgPoista;
    private javax.swing.JButton btMgTulosta;
    private javax.swing.JButton btMgTyhjenna;
    private javax.swing.JButton btTyhjenna;
    private javax.swing.JButton btValikko;
    private javax.swing.JComboBox<String> comboKirjasto;
    private javax.swing.JComboBox<String> comboKjsHaku;
    private javax.swing.JComboBox<String> comboManga;
    private javax.swing.JComboBox<String> comboMgHaku;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel lblKjsRivi;
    private javax.swing.JLabel lblMgRivi;
    private javax.swing.JTable tbKirjasto;
    private javax.swing.JTable tbManga;
    private javax.swing.JTextField txtKjsHaku;
    private javax.swing.JTextField txtKjsID;
    private javax.swing.JTextField txtKjsNro;
    private javax.swing.JTextField txtMgHaku;
    private javax.swing.JTextField txtMgID;
    private javax.swing.JTextField txtMgKieli;
    private javax.swing.JTextField txtMgKustantaja;
    private javax.swing.JTextField txtMgNimi;
    private javax.swing.JTextField txtMgTekija;
    // End of variables declaration//GEN-END:variables

    private void clear() {
        //Tyhjennetään teksti kentät
        txtMgNimi.setText(null);
        txtMgTekija.setText(null);
        txtMgKustantaja.setText(null);
        txtMgKieli.setText(null);
        txtKjsNro.setText(null);
    }

    private void rivinlasku() {
        /**
         * Lasketaan Kirjato-taulukon rivit ja lisätään lblKjsRivi-labeliin.
         * Lasketaan Manga-taulukon rivit ja lisätään lblMgRivi-labeliin.
         */
        int riviKjs = tbKirjasto.getRowCount();
        lblKjsRivi.setText("" + riviKjs + " ");
        int riviMg = tbManga.getRowCount();
        lblMgRivi.setText("" + riviMg + " ");
    }

    //MANGA
    private void tableloadMg(JTable jt) throws ClassNotFoundException, SQLException {
        //Luodaan taulukko malli
        DefaultTableModel dt = (DefaultTableModel) jt.getModel();
        //Asetetaan rivit aloittamaan 0
        dt.setRowCount(0);
        //Luodaan taulukko lajittelija ja asetetaan se manga taulukkoon
        TableRowSorter<TableModel> sorter;
        sorter = new TableRowSorter<TableModel>(dt);
        tbManga.setRowSorter(sorter);
        //Haetaan tiedot tietokannasta ja lisätään ne taulukkoon
        ResultSet rset = db.getData("SELECT * FROM MANGA");

        while (rset.next()) {
            Vector v = new Vector();
            v.add(rset.getString(1));
            v.add(rset.getString(2));
            v.add(rset.getString(3));
            v.add(rset.getString(4));
            v.add(rset.getString(5));

            dt.addRow(v);
        }
    }

    private void comboloadMg(JComboBox jl) throws ClassNotFoundException, SQLException {
       //Alustetaan comboManga
        comboManga.removeAllItems();
        //Haetaan tiedot tietokannasta ja lisätään ne valintaComboon. 
        ResultSet rset = db.getData("SELECT * FROM MANGA");
        while (rset.next()) {
            String pat = rset.getInt("ID") + " , " + rset.getString("NIMI") + " , " + rset.getString("KIELI");
            comboManga.addItem(pat);
        }
    }

    private void idloadManga(JTextField jText) throws ClassNotFoundException, SQLException {
        //Haetaan viimeisin vapaana oleva ID
        ResultSet rset = db.getData("select max(ID) from MANGA");
        while (rset.next()) {
            int i = rset.getInt(1);
            i = i + 1;
            jText.setText(String.valueOf(i));
        }
    }

    private void tableloadMgHaku(JTable jtm) throws ClassNotFoundException, SQLException {
        //Luodaan taulukko malli
        DefaultTableModel dt = (DefaultTableModel) jtm.getModel();
        //Asetetaan rivit aloittamaan 0
        dt.setRowCount(0);
        //Luodaan taulukko lajittelija ja asetetaan se manga taulukkoon
        TableRowSorter<TableModel> sorter;
        sorter = new TableRowSorter<TableModel>(dt);
        tbManga.setRowSorter(sorter);
        //Tarkistetaan ettei manga haku-kenttä ole tyhjä
        if (txtMgHaku.getText().isEmpty()) {
            //Jos haku kenttä on tyhjä niin näytetään viesti
            JOptionPane.showMessageDialog(null, "Anna haku kenttään hakusana!");
            //Kutsutaan tableloasMg-metodia manga taulukkoon
            tableloadMg(tbManga);

        } else {
            /**
             * Haetaan valittavan tiedon id comboManga:sta ja muutetaan se
             * int-muotoon. Haetaan tiedot tietokannasta. 
             * Lisätään ne taulukkoon
             */
            String valittu = (String) comboMgHaku.getSelectedItem();
            String hakuehto = txtMgHaku.getText();

            ResultSet rset = db.getData("SELECT * FROM MANGA WHERE " + valittu + " LIKE '%" + hakuehto + "%'");

            while (rset.next()) {
                Vector v = new Vector();
                v.add(rset.getString(1));
                v.add(rset.getString(2));
                v.add(rset.getString(3));
                v.add(rset.getString(4));
                v.add(rset.getString(5));

                dt.addRow(v);
            }
        }
    }

    //MGKIRJASTO
    private void tableloadKjs(JTable jt2) throws ClassNotFoundException, SQLException {
        //Luodaan taulukko malli
        DefaultTableModel dt = (DefaultTableModel) jt2.getModel();
        //Asetetaan rivit aloittamaan 0
        dt.setRowCount(0);
        //Luodaan taulukko lajittelija ja asetetaan se kirjasto taulukkoon
        TableRowSorter<TableModel> sorter;
        sorter = new TableRowSorter<TableModel>(dt);
        tbKirjasto.setRowSorter(sorter);

        //Haetaan tiedot tietokannasta ja lisätään ne taulukkoon
        ResultSet rset = db.getData("SELECT MGKIRJASTO.KIRJASTOID, MANGA.NIMI, MANGA.TEKIJA, MANGA.KUSTANTAJA, MANGA.KIELI, MGKIRJASTO.NRO "
                + "FROM MGKIRJASTO INNER JOIN MANGA ON MGKIRJASTO.ID_MANGA = MANGA.ID");

        while (rset.next()) {
            Vector v = new Vector();
            v.add(rset.getString(1));
            v.add(rset.getString(2));
            v.add(rset.getString(3));
            v.add(rset.getString(4));
            v.add(rset.getString(5));
            v.add(rset.getString(6));

            dt.addRow(v);
        }
    }

    private void comboload2(JComboBox jl2) throws ClassNotFoundException, SQLException {
        //Alustetaan comboKirjasto
        comboKirjasto.removeAllItems();
        //Haetaan tiedot tietokannasta ja lisätään ne valintaComboon. 
        ResultSet rset = db.getData("SELECT * FROM MGKIRJASTO INNER JOIN MANGA ON MGKIRJASTO.ID_MANGA = MANGA.ID");
        while (rset.next()) {
            String pat = rset.getInt("KIRJASTOID") + " , " + rset.getString("NIMI") + " , " + rset.getString("NRO");
            comboKirjasto.addItem(pat);
        }
    }

    private void idloadKirjasto(JTextField jText2) throws ClassNotFoundException, SQLException {
        //Haetaan viimeisin vapaana oleva ID
        ResultSet rset = db.getData("select max(KIRJASTOID) from MGKIRJASTO");
        while (rset.next()) {
            int i = rset.getInt(1);
            i = i + 1;
            jText2.setText(String.valueOf(i));
        }
    }

    private void tableloadKjsHaku(JTable jtk) throws ClassNotFoundException, SQLException {
        //Luodaan taulukko malli
        DefaultTableModel dt = (DefaultTableModel) jtk.getModel();
        //Asetetaan rivit aloittamaan 0
        dt.setRowCount(0);
        //Luodaan taulukko lajittelija ja asetetaan se kirjasto taulukkoon
        TableRowSorter<TableModel> sorter;
        sorter = new TableRowSorter<TableModel>(dt);
        tbKirjasto.setRowSorter(sorter);
         //Tarkistetaan ettei manga haku-kenttä ole tyhjä
        if (txtKjsHaku.getText().isEmpty()) {
            //Jos haku kenttä on tyhjä niin näytetään viesti
            JOptionPane.showMessageDialog(null, "Anna haku kenttään hakusana!");
            //Kutsutaan tableloasMg-metodia manga taulukkoon
            tableloadKjs(tbKirjasto);

        } else {
            /**
             * Haetaan valittavan tiedon id comboKirjasto:sta ja muutetaan se
             * int-muotoon. Haetaan tiedot tietokannasta. 
             * Lisätään ne taulukkoon
             */

            String valittu = (String) comboKjsHaku.getSelectedItem();
            String hakuehto = txtKjsHaku.getText();

            ResultSet rset = db.getData("SELECT MGKIRJASTO.KIRJASTOID, MANGA.NIMI, MANGA.TEKIJA, MANGA.KUSTANTAJA, MANGA.KIELI, MGKIRJASTO.NRO "
                    + "FROM MGKIRJASTO INNER JOIN MANGA ON MGKIRJASTO.ID_MANGA = MANGA.ID WHERE " + valittu + " LIKE '%" + hakuehto + "%'");

            while (rset.next()) {
                Vector v = new Vector();
                v.add(rset.getString(1));
                v.add(rset.getString(2));
                v.add(rset.getString(3));
                v.add(rset.getString(4));
                v.add(rset.getString(5));
                v.add(rset.getString(6));

                dt.addRow(v);
            }
        }
    }
}
