/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package omamgkirjasto;

import java.awt.Component;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author lentt
 */
public class MgKirjasto extends javax.swing.JFrame {

    luoYhteys db = new luoYhteys();

    /**
     * Creates new form MgKirjasto
     */
    public MgKirjasto() throws ClassNotFoundException, SQLException {
        initComponents();
        tableload1(tbManga);
        comboload(comboManga);
        idloadManga(txtMgID);

        tableload2(tbKirjasto);
        comboload2(comboKirjasto);
        idloadKirjasto(txtKjsID);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbKirjasto = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbManga = new javax.swing.JTable();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtMgID = new javax.swing.JTextField();
        txtMgNimi = new javax.swing.JTextField();
        txtMgTekija = new javax.swing.JTextField();
        txtMgKustantaja = new javax.swing.JTextField();
        txtMgKieli = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btMgLisaa = new javax.swing.JButton();
        btMgPaivita = new javax.swing.JButton();
        btMgPoista = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        comboManga = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txtKjsID = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtKjsNro = new javax.swing.JTextField();
        comboKirjasto = new javax.swing.JComboBox<>();
        jPanel7 = new javax.swing.JPanel();
        btKjsLisaa = new javax.swing.JButton();
        btKjsPaivita = new javax.swing.JButton();
        btKjsPoista = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jPanel11 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        comboMgHaku = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        txtMgHaku = new javax.swing.JTextField();
        btMgHae = new javax.swing.JButton();
        btMgTyhjenna = new javax.swing.JButton();
        jPanel12 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        comboKjsHaku = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        txtKjsHaku = new javax.swing.JTextField();
        btKjsHae = new javax.swing.JButton();
        btKjsTyhjenna = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbKirjasto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nimi", "Tekijä", "Kustantaja", "Kieli", "Nro"
            }
        ));
        tbKirjasto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbKirjastoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbKirjasto);
        if (tbKirjasto.getColumnModel().getColumnCount() > 0) {
            tbKirjasto.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 726, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Kirjasto", jPanel3);

        tbManga.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nimi", "Tekijä", "Kustantaja", "Kieli"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbManga.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbMangaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbManga);
        if (tbManga.getColumnModel().getColumnCount() > 0) {
            tbManga.getColumnModel().getColumn(0).setMaxWidth(50);
        }

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 726, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Manga", jPanel4);

        jTabbedPane2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel5.setText("Manga ID:");

        jLabel1.setText("Mangan nimi:");

        jLabel2.setText("Tekijä:");

        jLabel3.setText("Kustantaja:");

        jLabel4.setText("Kieli:");

        btMgLisaa.setText("Lisää");
        btMgLisaa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMgLisaaActionPerformed(evt);
            }
        });

        btMgPaivita.setText("Päivitä");
        btMgPaivita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMgPaivitaActionPerformed(evt);
            }
        });

        btMgPoista.setText("Poista");
        btMgPoista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMgPoistaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btMgPoista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btMgPaivita, javax.swing.GroupLayout.DEFAULT_SIZE, 75, Short.MAX_VALUE)
                    .addComponent(btMgLisaa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btMgLisaa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btMgPaivita)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btMgPoista)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(25, 25, 25)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMgKustantaja, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                            .addComponent(txtMgKieli)))
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addGap(31, 31, 31)
                            .addComponent(txtMgID))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(12, 12, 12)
                            .addComponent(txtMgNimi))
                        .addGroup(jPanel5Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(50, 50, 50)
                            .addComponent(txtMgTekija, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtMgID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtMgNimi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtMgTekija, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtMgKustantaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(txtMgKieli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        comboManga.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                comboMangaPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        comboManga.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                comboMangaMouseClicked(evt);
            }
        });
        comboManga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboMangaActionPerformed(evt);
            }
        });

        jLabel6.setText("Kirjasto ID:");

        jLabel7.setText("Nro:");

        btKjsLisaa.setText("Lisää");
        btKjsLisaa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btKjsLisaaActionPerformed(evt);
            }
        });

        btKjsPaivita.setText("Päivitä");
        btKjsPaivita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btKjsPaivitaActionPerformed(evt);
            }
        });

        btKjsPoista.setText("Poista");
        btKjsPoista.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btKjsPoistaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btKjsPaivita, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btKjsLisaa, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addGap(0, 1, Short.MAX_VALUE)
                        .addComponent(btKjsPoista)))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btKjsLisaa)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btKjsPaivita)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btKjsPoista)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(comboManga, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(comboKirjasto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(18, 18, 18)
                            .addComponent(txtKjsID, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel6Layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addGap(58, 58, 58)
                            .addComponent(txtKjsNro, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtKjsID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addComponent(comboManga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtKjsNro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(comboKirjasto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(95, 95, 95))
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(100, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Valinnat", jPanel8);

        jLabel9.setText("Manga haku:");

        jLabel10.setText("Valitse millä haetaan:");

        comboMgHaku.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NIMI", "TEKIJA", "KUSTANTAJA", "KIELI" }));

        jLabel11.setText("Kirjoita hakuehto:");

        btMgHae.setText("Hae");
        btMgHae.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMgHaeActionPerformed(evt);
            }
        });

        btMgTyhjenna.setText("Tyhjennä");
        btMgTyhjenna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMgTyhjennaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(comboMgHaku, 0, 155, Short.MAX_VALUE)
                            .addComponent(txtMgHaku))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btMgHae, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btMgTyhjenna))))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(comboMgHaku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btMgHae))
                .addGap(18, 18, 18)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtMgHaku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btMgTyhjenna))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel12.setText("Kirjasto haku:");

        jLabel13.setText("Valitse millä haetaan:");

        comboKjsHaku.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "NIMI", "TEKIJA", "KUSTANTAJA", "KIELI", "NRO" }));

        jLabel14.setText("Kirjoita hakuehto:");

        btKjsHae.setText("Hae");
        btKjsHae.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btKjsHaeActionPerformed(evt);
            }
        });

        btKjsTyhjenna.setText("Tyhjennä");
        btKjsTyhjenna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btKjsTyhjennaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(comboKjsHaku, 0, 157, Short.MAX_VALUE)
                            .addComponent(txtKjsHaku))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btKjsHae, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btKjsTyhjenna, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(comboKjsHaku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btKjsHae))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel13)))
                .addGap(18, 18, 18)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtKjsHaku, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btKjsTyhjenna))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(221, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Haku", jPanel9);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 528, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jLabel8.setFont(new java.awt.Font("Arial Black", 0, 48)); // NOI18N
        jLabel8.setText("Manga kirjasto");

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(122, 122, 122)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(122, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(316, 316, 316)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btMgLisaaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMgLisaaActionPerformed
        System.out.println("Alkaa21");
        try {

            //Lisätään tiedot tietokantaan
            db.putData("INSERT INTO MANGA(NIMI,TEKIJA,KUSTANTAJA,KIELI) "
                    + "values('" + txtMgNimi.getText() + "','" + txtMgTekija.getText() + "','" + txtMgKustantaja.getText()
                    + "','" + txtMgKieli.getText() + "')");

            System.out.println("Alkaa22");
            clear();
            tableload1(tbManga);
            comboload(comboManga);
            idloadManga(txtMgID);

            tableload2(tbKirjasto);
            comboload2(comboKirjasto);
            idloadKirjasto(txtKjsID);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MgKirjasto.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println(ex);
        } catch (SQLException ex) {
            Logger.getLogger(MgKirjasto.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println(ex);
        }
        System.out.println("Alkaa23");
    }//GEN-LAST:event_btMgLisaaActionPerformed

    private void tbMangaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbMangaMouseClicked
        //Klikkaamalla taulukkossa jotakin tietoa ne päivittyvät tekstikenttiin
        //Valitun tiedon nimi (paikka 0) lisätään Mangan nimi:-tekstikenttään
        txtMgID.setText(String.valueOf(tbManga.getValueAt(tbManga.getSelectedRow(), 0)));
        //Valitun tiedon nimi (paikka 1) lisätään Mangan nimi:-tekstikenttään
        txtMgNimi.setText(String.valueOf(tbManga.getValueAt(tbManga.getSelectedRow(), 1)));
        //Valitun tiedon tekijä (paikka 1) lisätään tekijä:-tekstikenttään
        txtMgTekija.setText(String.valueOf(tbManga.getValueAt(tbManga.getSelectedRow(), 2)));
        //Valitun tiedon kustantaja (paikka 2) lisätään kustantaja:-tekstikenttään
        txtMgKustantaja.setText(String.valueOf(tbManga.getValueAt(tbManga.getSelectedRow(), 3)));
        //Valitun tiedon kieli (paikka 3) lisätään kieli:-tekstikenttään
        txtMgKieli.setText(String.valueOf(tbManga.getValueAt(tbManga.getSelectedRow(), 4)));

        try {
            int valittuID = Integer.parseInt(String.valueOf(tbManga.getValueAt(tbManga.getSelectedRow(), 0)));
            ResultSet rset;
            //comboManga.removeAllItems();

            rset = db.getData("SELECT * FROM MANGA where ID= " + valittuID + "");

            while (rset.next()) {
                comboManga.setSelectedItem(rset.getInt("ID") + " " + rset.getString("NIMI") + " " + rset.getString("KIELI"));
            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MgKirjasto.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println(ex);
        } catch (SQLException ex) {
            Logger.getLogger(MgKirjasto.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println(ex);
        }

        //While silmukka

    }//GEN-LAST:event_tbMangaMouseClicked

    private void btMgPaivitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMgPaivitaActionPerformed
        try {
            //Luodaan statement (kysely)
            System.out.println("Päivitä1");

            String valinta = (String) comboManga.getSelectedItem();
            String[] nimet = valinta.split(" ");
            int mangaId = Integer.parseInt(nimet[0]);

            String nimi = txtMgNimi.getText();
            String tekija = txtMgTekija.getText();
            String kustantaja = txtMgKustantaja.getText();
            String kieli = txtMgKieli.getText();

            db.putData("UPDATE MANGA SET NIMI  ='" + nimi + "', TEKIJA = '" + tekija + "', KUSTANTAJA ='" + kustantaja + "',  KIELI='" + kieli + "'  WHERE ID = " + mangaId);

            System.out.println("Päivitä5");
            clear();
            tableload1(tbManga);
            comboload(comboManga);
            idloadManga(txtMgID);

            tableload2(tbKirjasto);
            comboload2(comboKirjasto);
            idloadKirjasto(txtKjsID);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MgKirjasto.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println(ex);
        } catch (SQLException ex) {
            Logger.getLogger(MgKirjasto.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println(ex);
        }
        System.out.println("Päivitä9");
    }//GEN-LAST:event_btMgPaivitaActionPerformed

    private void btMgPoistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMgPoistaActionPerformed
        try {
            String valinta = (String) comboManga.getSelectedItem();
            String[] nimet = valinta.split(" ");
            int mangaId = Integer.parseInt(nimet[0]);
            db.putData("DELETE FROM MANGA WHERE ID = " + mangaId);
            db.putData("DELETE FROM MGKIRJASTO WHERE ID_MANGA = " + mangaId);

            //Päivitetään taulukko, jotta uusimmat muutokset näkyvät
            clear();
            tableload1(tbManga);
            comboload(comboManga);
            idloadManga(txtMgID);

            tableload2(tbKirjasto);
            comboload2(comboKirjasto);
            idloadKirjasto(txtKjsID);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MgKirjasto.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MgKirjasto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btMgPoistaActionPerformed

    private void comboMangaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_comboMangaMouseClicked

    }//GEN-LAST:event_comboMangaMouseClicked

    private void comboMangaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboMangaActionPerformed

    }//GEN-LAST:event_comboMangaActionPerformed

    private void comboMangaPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_comboMangaPopupMenuWillBecomeInvisible
        try {

            String valinta = (String) comboManga.getSelectedItem();
            String[] nimet = valinta.split(" ");
            int mangaID = Integer.parseInt(nimet[0]);

            ResultSet rset = db.getData("SELECT * FROM MANGA WHERE ID =" + mangaID);
            while (rset.next()) {

                txtMgID.setText(rset.getString("ID"));
                txtMgNimi.setText(rset.getString("NIMI"));
                txtMgTekija.setText(rset.getString("TEKIJA"));
                txtMgKustantaja.setText(rset.getString("KUSTANTAJA"));
                txtMgKieli.setText(rset.getString("KIELI"));
            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MgKirjasto.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MgKirjasto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_comboMangaPopupMenuWillBecomeInvisible

    private void btKjsLisaaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btKjsLisaaActionPerformed
        System.out.println("Alkaa211");
        try {

            String valinta = (String) comboManga.getSelectedItem();
            String[] nimet = valinta.split(" ");
            int mangaId = Integer.parseInt(nimet[0]);
            System.out.println(mangaId);

            String sql = "SELECT * FROM MANGA WHERE ID = " + mangaId;
            ResultSet rset = db.getData(sql);
            // ResultSet rset2 = db.getData("SELECT * FROM MGKIRJASTO INNER JOIN MANGA  ON MGKIRJASTO.ID_MANGA = MANGA.ID");
            //Lisätään tiedot tietokantaan
            System.out.println("Välitarkistus");
            while (rset.next()) {
                System.out.println(rset.getInt("ID"));
                // while (rset2.next()) {
                db.putData("INSERT INTO MGKIRJASTO(ID_MANGA,NRO) VALUES(" + rset.getInt("ID") + ",'" + txtKjsNro.getText() + "')");

            }
            //}
            System.out.println("Alkaa222");
            clear();
            tableload1(tbManga);
            comboload(comboManga);
            idloadManga(txtMgID);

            tableload2(tbKirjasto);
            comboload2(comboKirjasto);
            idloadKirjasto(txtKjsID);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MgKirjasto.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println(ex);
        } catch (SQLException ex) {
            Logger.getLogger(MgKirjasto.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println(ex);
        }
        System.out.println("Alkaa233");
    }//GEN-LAST:event_btKjsLisaaActionPerformed

    private void btKjsPaivitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btKjsPaivitaActionPerformed
        try {
            //Luodaan statement (kysely)
            System.out.println("Päivitä1");

            String valinta = (String) comboManga.getSelectedItem();
            String[] nimet = valinta.split(" ");
            int mangaId = Integer.parseInt(nimet[0]);

            String valinta2 = (String) comboKirjasto.getSelectedItem();
            String[] nimet2 = valinta2.split(" ");
            int kirjastoId = Integer.parseInt(nimet[0]);

            String nro = txtKjsNro.getText();
            System.out.println(mangaId);
            System.out.println(kirjastoId);

            db.putData("UPDATE MGKIRJASTO SET ID_MANGA  =" + mangaId + ", NRO = '" + nro + "'  WHERE KIRJASTOID =" + kirjastoId);

            System.out.println("Päivitä5");
            clear();
            tableload1(tbManga);
            comboload(comboManga);
            idloadManga(txtMgID);

            tableload2(tbKirjasto);
            comboload2(comboKirjasto);
            idloadKirjasto(txtKjsID);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MgKirjasto.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println(ex);
        } catch (SQLException ex) {
            Logger.getLogger(MgKirjasto.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println(ex);
        }
        System.out.println("Päivitä9");
    }//GEN-LAST:event_btKjsPaivitaActionPerformed

    private void btKjsPoistaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btKjsPoistaActionPerformed
        try {
            String valinta = (String) comboKirjasto.getSelectedItem();
            String[] nimet = valinta.split(" ");
            int kirjastoId = Integer.parseInt(nimet[0]);

            db.putData("DELETE FROM MGKIRJASTO WHERE KIRJASTOID = " + kirjastoId);

            clear();
            tableload1(tbManga);
            comboload(comboManga);
            idloadManga(txtMgID);

            tableload2(tbKirjasto);
            comboload2(comboKirjasto);
            idloadKirjasto(txtKjsID);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MgKirjasto.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MgKirjasto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btKjsPoistaActionPerformed

    private void tbKirjastoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbKirjastoMouseClicked
        //Klikkaamalla taulukkossa jotakin tietoa ne päivittyvät tekstikenttiin
        //Valitun tiedon nimi (paikka 0) lisätään Mangan nimi:-tekstikenttään
        txtKjsID.setText(String.valueOf(tbKirjasto.getValueAt(tbKirjasto.getSelectedRow(), 0)));
        //Valitun tiedon nimi (paikka 1) lisätään Mangan nimi:-tekstikenttään
        txtMgNimi.setText(String.valueOf(tbKirjasto.getValueAt(tbKirjasto.getSelectedRow(), 1)));
        //Valitun tiedon tekijä (paikka 1) lisätään tekijä:-tekstikenttään
        txtMgTekija.setText(String.valueOf(tbKirjasto.getValueAt(tbKirjasto.getSelectedRow(), 2)));
        //Valitun tiedon kustantaja (paikka 2) lisätään kustantaja:-tekstikenttään
        txtMgKustantaja.setText(String.valueOf(tbKirjasto.getValueAt(tbKirjasto.getSelectedRow(), 3)));
        //Valitun tiedon kieli (paikka 3) lisätään kieli:-tekstikenttään
        txtMgKieli.setText(String.valueOf(tbKirjasto.getValueAt(tbKirjasto.getSelectedRow(), 4)));
        //Valitun tiedon kieli (paikka 3) lisätään kieli:-tekstikenttään
        txtKjsNro.setText(String.valueOf(tbKirjasto.getValueAt(tbKirjasto.getSelectedRow(), 5)));

        try {
            //Haetaan KirjastoID taulukosta ja muutetaan se int muotoon.
            int valittuKjsID = Integer.parseInt(String.valueOf(tbKirjasto.getValueAt(tbKirjasto.getSelectedRow(), 0)));
            //Haetaan tiedot comboManga-valikkoon
            ResultSet rset = db.getData("SELECT * FROM MGKIRJASTO INNER JOIN MANGA ON MGKIRJASTO.ID_MANGA = MANGA.ID WHERE KIRJASTOID= " + valittuKjsID + "");
            //Lisätään tiedot comboManga-valikkoon
            while (rset.next()) {
                comboManga.setSelectedItem(rset.getInt("ID_MANGA") + " " + rset.getString("NIMI") + " " + rset.getString("KIELI"));
                //Lisätään txtMgID-kenttään Manga ID 
                txtMgID.setText(rset.getString("ID"));
            }

            //Haetaan tiedot comboKirjasto-valikkoon
            ResultSet rset2 = db.getData("SELECT * FROM MGKIRJASTO INNER JOIN MANGA ON MGKIRJASTO.ID_MANGA = MANGA.ID WHERE KIRJASTOID= " + valittuKjsID + "");
            //Lisätään tiedot comboKirjasto-valikkoon
            while (rset2.next()) {
                comboKirjasto.setSelectedItem(rset2.getInt("KIRJASTOID") + " " + rset2.getString("NIMI") + " " + rset2.getString("NRO"));
            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MgKirjasto.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println(ex);
        } catch (SQLException ex) {
            Logger.getLogger(MgKirjasto.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println(ex);
        }

    }//GEN-LAST:event_tbKirjastoMouseClicked

    private void btMgHaeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMgHaeActionPerformed
        try {
            // TODO add your handling code here:
            tableloadMgHaku(tbManga);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MgKirjasto.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MgKirjasto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btMgHaeActionPerformed

    private void btMgTyhjennaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMgTyhjennaActionPerformed
        // TODO add your handling code here:
        txtMgHaku.setText(null);
        try {
            tableload1(tbManga);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MgKirjasto.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MgKirjasto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btMgTyhjennaActionPerformed

    private void btKjsHaeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btKjsHaeActionPerformed
        try {
            // TODO add your handling code here:
            tableloadKjsHaku(tbKirjasto);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MgKirjasto.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MgKirjasto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btKjsHaeActionPerformed

    private void btKjsTyhjennaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btKjsTyhjennaActionPerformed
        // TODO add your handling code here:
        txtKjsHaku.setText(null);
        try {
            tableload2(tbKirjasto);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(MgKirjasto.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(MgKirjasto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btKjsTyhjennaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MgKirjasto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MgKirjasto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MgKirjasto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MgKirjasto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MgKirjasto().setVisible(true);
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(MgKirjasto.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(MgKirjasto.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btKjsHae;
    private javax.swing.JButton btKjsLisaa;
    private javax.swing.JButton btKjsPaivita;
    private javax.swing.JButton btKjsPoista;
    private javax.swing.JButton btKjsTyhjenna;
    private javax.swing.JButton btMgHae;
    private javax.swing.JButton btMgLisaa;
    private javax.swing.JButton btMgPaivita;
    private javax.swing.JButton btMgPoista;
    private javax.swing.JButton btMgTyhjenna;
    private javax.swing.JComboBox<String> comboKirjasto;
    private javax.swing.JComboBox<String> comboKjsHaku;
    private javax.swing.JComboBox<String> comboManga;
    private javax.swing.JComboBox<String> comboMgHaku;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable tbKirjasto;
    private javax.swing.JTable tbManga;
    private javax.swing.JTextField txtKjsHaku;
    private javax.swing.JTextField txtKjsID;
    private javax.swing.JTextField txtKjsNro;
    private javax.swing.JTextField txtMgHaku;
    private javax.swing.JTextField txtMgID;
    private javax.swing.JTextField txtMgKieli;
    private javax.swing.JTextField txtMgKustantaja;
    private javax.swing.JTextField txtMgNimi;
    private javax.swing.JTextField txtMgTekija;
    // End of variables declaration//GEN-END:variables

    private void clear() {
        //Tyhjennetään teksti kentät
        txtMgNimi.setText(null);
        txtMgTekija.setText(null);
        txtMgKustantaja.setText(null);
        txtMgKieli.setText(null);
        txtKjsNro.setText(null);
    }

    //MANGA
    private void tableload1(JTable jt) throws ClassNotFoundException, SQLException {
        DefaultTableModel dt = (DefaultTableModel) jt.getModel();
        //Asetetaan rivit aloittamaan 0
        dt.setRowCount(0);
        //Haetaan tiedot tietokannasta ja lisätään ne taulukkoon
        ResultSet rset = db.getData("SELECT * FROM MANGA");

        while (rset.next()) {
            Vector v = new Vector();
            v.add(rset.getString(1));
            v.add(rset.getString(2));
            v.add(rset.getString(3));
            v.add(rset.getString(4));
            v.add(rset.getString(5));

            dt.addRow(v);
        }
    }

    private void comboload(JComboBox jl) throws ClassNotFoundException, SQLException {
        comboManga.removeAllItems();
        //Haetaan tiedot tietokannasta ja lisätään ne valintaComboon. 
        ResultSet rset = db.getData("SELECT * FROM MANGA");
        while (rset.next()) {
            String pat = rset.getInt("ID") + " " + rset.getString("NIMI") + " " + rset.getString("KIELI");
            comboManga.addItem(pat);
        }
    }

    private void idloadManga(JTextField jText) throws ClassNotFoundException, SQLException {
        //Haetaan viimeisin vapaana oleva ID
        ResultSet rset = db.getData("select max(ID) from MANGA");
        while (rset.next()) {
            int i = rset.getInt(1);
            i = i + 1;
            jText.setText(String.valueOf(i));
        }
    }

    private void tableloadMgHaku(JTable jtm) throws ClassNotFoundException, SQLException {
        DefaultTableModel dt = (DefaultTableModel) jtm.getModel();
        //Asetetaan rivit aloittamaan 0
        dt.setRowCount(0);

        String valittu = (String) comboMgHaku.getSelectedItem();
        String hakuehto = txtMgHaku.getText();

        ResultSet rset = db.getData("SELECT * FROM MANGA WHERE " + valittu + "='" + hakuehto + "'");

        while (rset.next()) {
            Vector v = new Vector();
            v.add(rset.getString(1));
            v.add(rset.getString(2));
            v.add(rset.getString(3));
            v.add(rset.getString(4));
            v.add(rset.getString(5));

            dt.addRow(v);
        }
    }

    //MGKIRJASTO
    private void tableload2(JTable jt2) throws ClassNotFoundException, SQLException {
        DefaultTableModel dt2 = (DefaultTableModel) jt2.getModel();
        //Asetetaan rivit aloittamaan 0
        dt2.setRowCount(0);
        //Haetaan tiedot tietokannasta ja lisätään ne taulukkoon
        ResultSet rset = db.getData("SELECT MGKIRJASTO.KIRJASTOID, MANGA.NIMI, MANGA.TEKIJA, MANGA.KUSTANTAJA, MANGA.KIELI, MGKIRJASTO.NRO "
                + "FROM MGKIRJASTO INNER JOIN MANGA ON MGKIRJASTO.ID_MANGA = MANGA.ID");

        while (rset.next()) {
            Vector v = new Vector();
            v.add(rset.getString(1));
            v.add(rset.getString(2));
            v.add(rset.getString(3));
            v.add(rset.getString(4));
            v.add(rset.getString(5));
            v.add(rset.getString(6));

            dt2.addRow(v);
        }
    }

    private void comboload2(JComboBox jl2) throws ClassNotFoundException, SQLException {
        comboKirjasto.removeAllItems();
        //Haetaan tiedot tietokannasta ja lisätään ne valintaComboon. 
        ResultSet rset = db.getData("SELECT * FROM MGKIRJASTO INNER JOIN MANGA ON MGKIRJASTO.ID_MANGA = MANGA.ID");
        while (rset.next()) {
            String pat = rset.getInt("KIRJASTOID") + " " + rset.getString("NIMI") + " " + rset.getString("NRO");
            comboKirjasto.addItem(pat);
        }
    }

    private void idloadKirjasto(JTextField jText2) throws ClassNotFoundException, SQLException {
        //Haetaan viimeisin vapaana oleva ID
        ResultSet rset = db.getData("select max(KIRJASTOID) from MGKIRJASTO");
        while (rset.next()) {
            int i = rset.getInt(1);
            i = i + 1;
            jText2.setText(String.valueOf(i));
        }
    }
    private void tableloadKjsHaku(JTable jtk) throws ClassNotFoundException, SQLException {
        DefaultTableModel dt = (DefaultTableModel) jtk.getModel();
        //Asetetaan rivit aloittamaan 0
        dt.setRowCount(0);

        String valittu = (String) comboKjsHaku.getSelectedItem();
        String hakuehto = txtKjsHaku.getText();

        ResultSet rset = db.getData("SELECT MGKIRJASTO.KIRJASTOID, MANGA.NIMI, MANGA.TEKIJA, MANGA.KUSTANTAJA, MANGA.KIELI, MGKIRJASTO.NRO "
                + "FROM MGKIRJASTO INNER JOIN MANGA ON MGKIRJASTO.ID_MANGA = MANGA.ID WHERE " + valittu + "='" + hakuehto + "'");

        while (rset.next()) {
            Vector v = new Vector();
            v.add(rset.getString(1));
            v.add(rset.getString(2));
            v.add(rset.getString(3));
            v.add(rset.getString(4));
            v.add(rset.getString(5));
            v.add(rset.getString(6));

            dt.addRow(v);
        }
    }
}
